# Generated by Django 4.0.2 on 2022-05-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_survey_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='imageURL',
            field=models.CharField(default='https://i.imgur.com/uMWCK7i.jpg', max_length=255),
            preserve_default=False,
        ),
    ]
