# Generated by Django 4.0.2 on 2022-05-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_survey_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published'), ('C', 'Closed')], default='D', max_length=1, verbose_name='Status'),
        ),
    ]
